In [2]:
import pandas as pd

product = pd.read_csv(r'../data/product_catalog.csv')
userdata = pd.read_csv(r'../data/user_profiles.csv')

In [ ]:
product.shape

(1000, 10)

In [7]:
product[product['category']=='Smartphone'].head(10)

,product_id,name,category,brand,price,description,specifications,features,rating,stock_count
0,1,Oppo F23 Pro,Smartphone,Oppo,148681,Innovative smartphone designed for creativity ...,"Display: 11.6-inch Retina, Storage: 64GB, RAM:...","5G, High refresh rate, Fingerprint, Face unloc...",4.6,81
1,2,Moto G84,Smartphone,Moto,38982,High-performance smartphone designed for enter...,"Display: 9.0-inch OLED, Storage: 64GB, RAM: 8G...","Face unlock, Water resistant, 5G, High refresh...",4.5,95
3,4,Samsung Galaxy A54,Smartphone,Samsung,243833,Versatile smartphone designed for professional...,"Display: 7.4-inch LCD, Storage: 256GB, RAM: 16...","Wireless charging, Fast charging, Water resist...",3.6,13
7,8,Samsung Galaxy Z Flip 5,Smartphone,Samsung,117428,Powerful smartphone designed for daily use wit...,"Display: 12.1-inch Retina, Storage: 1TB, RAM: ...","Multiple cameras, AMOLED display, Fingerprint,...",4.2,34
12,13,Apple iPhone SE (2022),Smartphone,Apple,207844,Reliable smartphone designed for content creat...,"Display: 8.2-inch OLED, Storage: 128GB, RAM: 8...","Water resistant, Multiple cameras, Wireless ch...",4.7,20
14,15,Samsung Galaxy S23 FE,Smartphone,Samsung,161948,Versatile smartphone designed for business wit...,"Display: 7.1-inch Retina, Storage: 64GB, RAM: ...","AI photography, Face unlock, High refresh rate...",4.7,93
16,17,Realme GT 2 Pro,Smartphone,Realme,166727,Reliable smartphone designed for entertainment...,"Display: 12.2-inch AMOLED, Storage: 1TB, RAM: ...","AMOLED display, 5G, Face unlock, AI photograph...",3.7,19
20,21,Oppo F23 Pro,Smartphone,Oppo,243442,Advanced smartphone designed for creativity wi...,"Display: 10.1-inch LCD, Storage: 128GB, RAM: 8...","AMOLED display, Fingerprint, Wireless charging...",4.9,91
21,22,Vivo X100 Pro,Smartphone,Vivo,153311,Sleek smartphone designed for professional wor...,"Display: 11.8-inch OLED, Storage: 512GB, RAM: ...","5G, Face unlock, Fingerprint, Wireless chargin...",4.0,7
24,25,Xiaomi Redmi Note 13 Pro+,Smartphone,Xiaomi,178163,High-performance smartphone designed for creat...,"Display: 11.1-inch OLED, Storage: 1TB, RAM: 6G...","Water resistant, 5G, Face unlock, AI photograp...",4.3,8

In [7]:
converter = userdata.pivot_table( index= 'interests', columns='tech_savviness', values='ser_id', aggfunc='count', margins=True)

In [8]:
converter

tech_savviness  Advanced  Beginner  Intermediate   All
interests
business              31        58            74   163
education             46        50            62   158
entertainment         37        51            62   150
gaming                26        72            67   165
photography           34        68            87   189
travel                49        66            60   175
All                  223       365           412  1000